# Docker Compose file for the DEVELOPMENT environment.
# Ports are now sourced from the .env file for better configuration.

version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      # Expose the PostgreSQL port to the host machine.
      - "${POSTGRES_PORT}:5432"

  # Redis Caching Service
  redis:
    image: redis:6-alpine
    ports:
      # Expose the Redis port to the host machine.
      - "${REDIS_PORT}:6379"

volumes:
  # Define the named volume for persisting PostgreSQL data.
  postgres_data:
