# Docker Compose file for the PRODUCTION environment.
# Ports are now sourced from the .env file.

version: '3.8'

services:
  # Backend Application Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      # Expose the application's port to the host.
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  # PostgreSQL Database Service
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # Redis Caching Service
  redis:
    image: redis:6-alpine

volumes:
  # Define the named volume for PostgreSQL data persistence.
  postgres_data:
